//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKTIO_App
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Dolzhnost.
    /// </summary>
    // *** Start programmer edit section *** (Dolzhnost CustomAttributes)

    // *** End programmer edit section *** (Dolzhnost CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("DolzhnostE", new string[] {
            "Naimenovanie as \'Наименование\'"})]
    [View("DolzhnostL", new string[] {
            "Naimenovanie as \'Наименование\'"})]
    public class Dolzhnost : ICSSoft.STORMNET.DataObject
    {
        
        private string fNaimenovanie;
        
        // *** Start programmer edit section *** (Dolzhnost CustomMembers)

        // *** End programmer edit section *** (Dolzhnost CustomMembers)

        
        /// <summary>
        /// Naimenovanie.
        /// </summary>
        // *** Start programmer edit section *** (Dolzhnost.Naimenovanie CustomAttributes)

        // *** End programmer edit section *** (Dolzhnost.Naimenovanie CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Naimenovanie
        {
            get
            {
                // *** Start programmer edit section *** (Dolzhnost.Naimenovanie Get start)

                // *** End programmer edit section *** (Dolzhnost.Naimenovanie Get start)
                string result = this.fNaimenovanie;
                // *** Start programmer edit section *** (Dolzhnost.Naimenovanie Get end)

                // *** End programmer edit section *** (Dolzhnost.Naimenovanie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Dolzhnost.Naimenovanie Set start)

                // *** End programmer edit section *** (Dolzhnost.Naimenovanie Set start)
                this.fNaimenovanie = value;
                // *** Start programmer edit section *** (Dolzhnost.Naimenovanie Set end)

                // *** End programmer edit section *** (Dolzhnost.Naimenovanie Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "DolzhnostE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DolzhnostE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DolzhnostE", typeof(UKTIO_App.Dolzhnost));
                }
            }
            
            /// <summary>
            /// "DolzhnostL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DolzhnostL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DolzhnostL", typeof(UKTIO_App.Dolzhnost));
                }
            }
        }
    }
}
