//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKTIO_App
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Oborudovanie.
    /// </summary>
    // *** Start programmer edit section *** (Oborudovanie CustomAttributes)

    // *** End programmer edit section *** (Oborudovanie CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("OborudovanieE", new string[] {
            "InvNomer as \'Инвентарный номер\'",
            "Naimenovanie as \'Наименование\'",
            "Harakteristiki as \'Характеристики\'",
            "DataPokupki as \'Дата покупки\'",
            "Cena as \'Цена\'",
            "Status as \'Статус\'",
            "TipOborudovaniya as \'Тип оборудования\'",
            "TipOborudovaniya.Naimenovanie as \'Наименование\'",
            "Sotrudnik as \'Сотрудник\'",
            "Sotrudnik.FIO",
            "Sotrudnik.Imya",
            "Sotrudnik.Otchestvo",
            "Sotrudnik.Familia as \'Familia\'"}, Hidden=new string[] {
            "TipOborudovaniya.Naimenovanie",
            "Sotrudnik.FIO",
            "Sotrudnik.Imya",
            "Sotrudnik.Otchestvo",
            "Sotrudnik.Familia"})]
    [MasterViewDefineAttribute("OborudovanieE", "TipOborudovaniya", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Naimenovanie")]
    [MasterViewDefineAttribute("OborudovanieE", "Sotrudnik", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "FIO")]
    [View("OborudovanieL", new string[] {
            "InvNomer as \'Инвентарный номер\'",
            "Naimenovanie as \'Наименование\'",
            "Harakteristiki as \'Характеристики\'",
            "DataPokupki as \'Дата покупки\'",
            "Cena as \'Цена\'",
            "Status as \'Статус\'",
            "TipOborudovaniya.Naimenovanie as \'Тип оборудования\'",
            "Sotrudnik.FIO as \'Сотрудник\'"})]
    public class Oborudovanie : ICSSoft.STORMNET.DataObject
    {
        
        private int fInvNomer;
        
        private string fNaimenovanie;
        
        private string fHarakteristiki;
        
        private System.DateTime fDataPokupki = System.DateTime.Now;
        
        private double fCena;
        
        private UKTIO_App.tStatus fStatus;
        
        private UKTIO_App.TipOborudovaniya fTipOborudovaniya;
        
        private UKTIO_App.Sotrudnik fSotrudnik;
        
        // *** Start programmer edit section *** (Oborudovanie CustomMembers)

        // *** End programmer edit section *** (Oborudovanie CustomMembers)

        
        /// <summary>
        /// InvNomer.
        /// </summary>
        // *** Start programmer edit section *** (Oborudovanie.InvNomer CustomAttributes)

        // *** End programmer edit section *** (Oborudovanie.InvNomer CustomAttributes)
        public virtual int InvNomer
        {
            get
            {
                // *** Start programmer edit section *** (Oborudovanie.InvNomer Get start)

                // *** End programmer edit section *** (Oborudovanie.InvNomer Get start)
                int result = this.fInvNomer;
                // *** Start programmer edit section *** (Oborudovanie.InvNomer Get end)

                // *** End programmer edit section *** (Oborudovanie.InvNomer Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Oborudovanie.InvNomer Set start)

                // *** End programmer edit section *** (Oborudovanie.InvNomer Set start)
                this.fInvNomer = value;
                // *** Start programmer edit section *** (Oborudovanie.InvNomer Set end)

                // *** End programmer edit section *** (Oborudovanie.InvNomer Set end)
            }
        }
        
        /// <summary>
        /// Naimenovanie.
        /// </summary>
        // *** Start programmer edit section *** (Oborudovanie.Naimenovanie CustomAttributes)

        // *** End programmer edit section *** (Oborudovanie.Naimenovanie CustomAttributes)
        [StrLen(255)]
        public virtual string Naimenovanie
        {
            get
            {
                // *** Start programmer edit section *** (Oborudovanie.Naimenovanie Get start)

                // *** End programmer edit section *** (Oborudovanie.Naimenovanie Get start)
                string result = this.fNaimenovanie;
                // *** Start programmer edit section *** (Oborudovanie.Naimenovanie Get end)

                // *** End programmer edit section *** (Oborudovanie.Naimenovanie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Oborudovanie.Naimenovanie Set start)

                // *** End programmer edit section *** (Oborudovanie.Naimenovanie Set start)
                this.fNaimenovanie = value;
                // *** Start programmer edit section *** (Oborudovanie.Naimenovanie Set end)

                // *** End programmer edit section *** (Oborudovanie.Naimenovanie Set end)
            }
        }
        
        /// <summary>
        /// Harakteristiki.
        /// </summary>
        // *** Start programmer edit section *** (Oborudovanie.Harakteristiki CustomAttributes)

        // *** End programmer edit section *** (Oborudovanie.Harakteristiki CustomAttributes)
        [StrLen(255)]
        public virtual string Harakteristiki
        {
            get
            {
                // *** Start programmer edit section *** (Oborudovanie.Harakteristiki Get start)

                // *** End programmer edit section *** (Oborudovanie.Harakteristiki Get start)
                string result = this.fHarakteristiki;
                // *** Start programmer edit section *** (Oborudovanie.Harakteristiki Get end)

                // *** End programmer edit section *** (Oborudovanie.Harakteristiki Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Oborudovanie.Harakteristiki Set start)

                // *** End programmer edit section *** (Oborudovanie.Harakteristiki Set start)
                this.fHarakteristiki = value;
                // *** Start programmer edit section *** (Oborudovanie.Harakteristiki Set end)

                // *** End programmer edit section *** (Oborudovanie.Harakteristiki Set end)
            }
        }
        
        /// <summary>
        /// DataPokupki.
        /// </summary>
        // *** Start programmer edit section *** (Oborudovanie.DataPokupki CustomAttributes)

        // *** End programmer edit section *** (Oborudovanie.DataPokupki CustomAttributes)
        public virtual System.DateTime DataPokupki
        {
            get
            {
                // *** Start programmer edit section *** (Oborudovanie.DataPokupki Get start)

                // *** End programmer edit section *** (Oborudovanie.DataPokupki Get start)
                System.DateTime result = this.fDataPokupki;
                // *** Start programmer edit section *** (Oborudovanie.DataPokupki Get end)

                // *** End programmer edit section *** (Oborudovanie.DataPokupki Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Oborudovanie.DataPokupki Set start)

                // *** End programmer edit section *** (Oborudovanie.DataPokupki Set start)
                this.fDataPokupki = value;
                // *** Start programmer edit section *** (Oborudovanie.DataPokupki Set end)

                // *** End programmer edit section *** (Oborudovanie.DataPokupki Set end)
            }
        }
        
        /// <summary>
        /// Cena.
        /// </summary>
        // *** Start programmer edit section *** (Oborudovanie.Cena CustomAttributes)

        // *** End programmer edit section *** (Oborudovanie.Cena CustomAttributes)
        public virtual double Cena
        {
            get
            {
                // *** Start programmer edit section *** (Oborudovanie.Cena Get start)

                // *** End programmer edit section *** (Oborudovanie.Cena Get start)
                double result = this.fCena;
                // *** Start programmer edit section *** (Oborudovanie.Cena Get end)

                // *** End programmer edit section *** (Oborudovanie.Cena Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Oborudovanie.Cena Set start)

                // *** End programmer edit section *** (Oborudovanie.Cena Set start)
                this.fCena = value;
                // *** Start programmer edit section *** (Oborudovanie.Cena Set end)

                // *** End programmer edit section *** (Oborudovanie.Cena Set end)
            }
        }
        
        /// <summary>
        /// Status.
        /// </summary>
        // *** Start programmer edit section *** (Oborudovanie.Status CustomAttributes)

        // *** End programmer edit section *** (Oborudovanie.Status CustomAttributes)
        public virtual UKTIO_App.tStatus Status
        {
            get
            {
                // *** Start programmer edit section *** (Oborudovanie.Status Get start)

                // *** End programmer edit section *** (Oborudovanie.Status Get start)
                UKTIO_App.tStatus result = this.fStatus;
                // *** Start programmer edit section *** (Oborudovanie.Status Get end)

                // *** End programmer edit section *** (Oborudovanie.Status Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Oborudovanie.Status Set start)

                // *** End programmer edit section *** (Oborudovanie.Status Set start)
                this.fStatus = value;
                // *** Start programmer edit section *** (Oborudovanie.Status Set end)

                // *** End programmer edit section *** (Oborudovanie.Status Set end)
            }
        }
        
        /// <summary>
        /// Oborudovanie.
        /// </summary>
        // *** Start programmer edit section *** (Oborudovanie.TipOborudovaniya CustomAttributes)

        // *** End programmer edit section *** (Oborudovanie.TipOborudovaniya CustomAttributes)
        [PropertyStorage(new string[] {
                "TipOborudovaniya"})]
        [NotNull()]
        public virtual UKTIO_App.TipOborudovaniya TipOborudovaniya
        {
            get
            {
                // *** Start programmer edit section *** (Oborudovanie.TipOborudovaniya Get start)

                // *** End programmer edit section *** (Oborudovanie.TipOborudovaniya Get start)
                UKTIO_App.TipOborudovaniya result = this.fTipOborudovaniya;
                // *** Start programmer edit section *** (Oborudovanie.TipOborudovaniya Get end)

                // *** End programmer edit section *** (Oborudovanie.TipOborudovaniya Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Oborudovanie.TipOborudovaniya Set start)

                // *** End programmer edit section *** (Oborudovanie.TipOborudovaniya Set start)
                this.fTipOborudovaniya = value;
                // *** Start programmer edit section *** (Oborudovanie.TipOborudovaniya Set end)

                // *** End programmer edit section *** (Oborudovanie.TipOborudovaniya Set end)
            }
        }
        
        /// <summary>
        /// Oborudovanie.
        /// </summary>
        // *** Start programmer edit section *** (Oborudovanie.Sotrudnik CustomAttributes)

        // *** End programmer edit section *** (Oborudovanie.Sotrudnik CustomAttributes)
        [PropertyStorage(new string[] {
                "Sotrudnik"})]
        [NotNull()]
        public virtual UKTIO_App.Sotrudnik Sotrudnik
        {
            get
            {
                // *** Start programmer edit section *** (Oborudovanie.Sotrudnik Get start)

                // *** End programmer edit section *** (Oborudovanie.Sotrudnik Get start)
                UKTIO_App.Sotrudnik result = this.fSotrudnik;
                // *** Start programmer edit section *** (Oborudovanie.Sotrudnik Get end)

                // *** End programmer edit section *** (Oborudovanie.Sotrudnik Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Oborudovanie.Sotrudnik Set start)

                // *** End programmer edit section *** (Oborudovanie.Sotrudnik Set start)
                this.fSotrudnik = value;
                // *** Start programmer edit section *** (Oborudovanie.Sotrudnik Set end)

                // *** End programmer edit section *** (Oborudovanie.Sotrudnik Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "OborudovanieE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OborudovanieE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OborudovanieE", typeof(UKTIO_App.Oborudovanie));
                }
            }
            
            /// <summary>
            /// "OborudovanieL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OborudovanieL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OborudovanieL", typeof(UKTIO_App.Oborudovanie));
                }
            }
        }
    }
}
