//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKTIO_App
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Sotrudnik.
    /// </summary>
    // *** Start programmer edit section *** (Sotrudnik CustomAttributes)

    // *** End programmer edit section *** (Sotrudnik CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SotrudnikE", new string[] {
            "Familia as \'Фамилия\'",
            "Imya as \'Имя\'",
            "Otchestvo as \'Отчество\'",
            "Tel as \'Телефонl\'",
            "Email as \'Емейл\'",
            "NomerKabineta as \'Номер кабинета\'",
            "Dolzhnost as \'Должность\'",
            "Dolzhnost.Naimenovanie as \'Наименование\'",
            "Organizaciya as \'Организация\'",
            "Organizaciya.Nazvanie as \'Nazvanie\'"}, Hidden=new string[] {
            "Dolzhnost.Naimenovanie",
            "Organizaciya.Nazvanie"})]
    [MasterViewDefineAttribute("SotrudnikE", "Dolzhnost", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Naimenovanie")]
    [MasterViewDefineAttribute("SotrudnikE", "Organizaciya", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Nazvanie")]
    [View("SotrudnikL", new string[] {
            "Familia as \'Фамилия\'",
            "Imya as \'Имя\'",
            "Otchestvo as \'отчество\'",
            "Tel as \'Телефон\'",
            "Email as \'Емейл\'",
            "NomerKabineta as \'Номер кабинета\'",
            "Dolzhnost.Naimenovanie as \'Наименование\'",
            "Organizaciya.Nazvanie as \'Название\'"})]
    public class Sotrudnik : ICSSoft.STORMNET.DataObject
    {
        
        private string fFamilia;
        
        private string fImya;
        
        private string fOtchestvo;
        
        private string fTel;
        
        private string fEmail;
        
        private int fNomerKabineta;
        
        private UKTIO_App.Dolzhnost fDolzhnost;
        
        private UKTIO_App.Organizaciya fOrganizaciya;
        
        // *** Start programmer edit section *** (Sotrudnik CustomMembers)

        // *** End programmer edit section *** (Sotrudnik CustomMembers)

        
        /// <summary>
        /// Familia.
        /// </summary>
        // *** Start programmer edit section *** (Sotrudnik.Familia CustomAttributes)

        // *** End programmer edit section *** (Sotrudnik.Familia CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Familia
        {
            get
            {
                // *** Start programmer edit section *** (Sotrudnik.Familia Get start)

                // *** End programmer edit section *** (Sotrudnik.Familia Get start)
                string result = this.fFamilia;
                // *** Start programmer edit section *** (Sotrudnik.Familia Get end)

                // *** End programmer edit section *** (Sotrudnik.Familia Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sotrudnik.Familia Set start)

                // *** End programmer edit section *** (Sotrudnik.Familia Set start)
                this.fFamilia = value;
                // *** Start programmer edit section *** (Sotrudnik.Familia Set end)

                // *** End programmer edit section *** (Sotrudnik.Familia Set end)
            }
        }
        
        /// <summary>
        /// Imya.
        /// </summary>
        // *** Start programmer edit section *** (Sotrudnik.Imya CustomAttributes)

        // *** End programmer edit section *** (Sotrudnik.Imya CustomAttributes)
        [StrLen(255)]
        public virtual string Imya
        {
            get
            {
                // *** Start programmer edit section *** (Sotrudnik.Imya Get start)

                // *** End programmer edit section *** (Sotrudnik.Imya Get start)
                string result = this.fImya;
                // *** Start programmer edit section *** (Sotrudnik.Imya Get end)

                // *** End programmer edit section *** (Sotrudnik.Imya Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sotrudnik.Imya Set start)

                // *** End programmer edit section *** (Sotrudnik.Imya Set start)
                this.fImya = value;
                // *** Start programmer edit section *** (Sotrudnik.Imya Set end)

                // *** End programmer edit section *** (Sotrudnik.Imya Set end)
            }
        }
        
        /// <summary>
        /// Otchestvo.
        /// </summary>
        // *** Start programmer edit section *** (Sotrudnik.Otchestvo CustomAttributes)

        // *** End programmer edit section *** (Sotrudnik.Otchestvo CustomAttributes)
        [StrLen(255)]
        public virtual string Otchestvo
        {
            get
            {
                // *** Start programmer edit section *** (Sotrudnik.Otchestvo Get start)

                // *** End programmer edit section *** (Sotrudnik.Otchestvo Get start)
                string result = this.fOtchestvo;
                // *** Start programmer edit section *** (Sotrudnik.Otchestvo Get end)

                // *** End programmer edit section *** (Sotrudnik.Otchestvo Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sotrudnik.Otchestvo Set start)

                // *** End programmer edit section *** (Sotrudnik.Otchestvo Set start)
                this.fOtchestvo = value;
                // *** Start programmer edit section *** (Sotrudnik.Otchestvo Set end)

                // *** End programmer edit section *** (Sotrudnik.Otchestvo Set end)
            }
        }
        
        /// <summary>
        /// FIO.
        /// </summary>
        // *** Start programmer edit section *** (Sotrudnik.FIO CustomAttributes)

        // *** End programmer edit section *** (Sotrudnik.FIO CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [StrLen(255)]
        [DataServiceExpression(typeof(ICSSoft.STORMNET.Business.SQLDataService), "@Familia@ + \' \' + @Imya@")]
        public virtual string FIO
        {
            get
            {
                // *** Start programmer edit section *** (Sotrudnik.FIO Get)

                return $"{this.Familia} {this.Imya}";
                // *** End programmer edit section *** (Sotrudnik.FIO Get)
            }
            set
            {
                // *** Start programmer edit section *** (Sotrudnik.FIO Set)

                // *** End programmer edit section *** (Sotrudnik.FIO Set)
            }
        }
        
        /// <summary>
        /// Tel.
        /// </summary>
        // *** Start programmer edit section *** (Sotrudnik.Tel CustomAttributes)

        // *** End programmer edit section *** (Sotrudnik.Tel CustomAttributes)
        [StrLen(255)]
        public virtual string Tel
        {
            get
            {
                // *** Start programmer edit section *** (Sotrudnik.Tel Get start)

                // *** End programmer edit section *** (Sotrudnik.Tel Get start)
                string result = this.fTel;
                // *** Start programmer edit section *** (Sotrudnik.Tel Get end)

                // *** End programmer edit section *** (Sotrudnik.Tel Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sotrudnik.Tel Set start)

                // *** End programmer edit section *** (Sotrudnik.Tel Set start)
                this.fTel = value;
                // *** Start programmer edit section *** (Sotrudnik.Tel Set end)

                // *** End programmer edit section *** (Sotrudnik.Tel Set end)
            }
        }
        
        /// <summary>
        /// Email.
        /// </summary>
        // *** Start programmer edit section *** (Sotrudnik.Email CustomAttributes)

        // *** End programmer edit section *** (Sotrudnik.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                // *** Start programmer edit section *** (Sotrudnik.Email Get start)

                // *** End programmer edit section *** (Sotrudnik.Email Get start)
                string result = this.fEmail;
                // *** Start programmer edit section *** (Sotrudnik.Email Get end)

                // *** End programmer edit section *** (Sotrudnik.Email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sotrudnik.Email Set start)

                // *** End programmer edit section *** (Sotrudnik.Email Set start)
                this.fEmail = value;
                // *** Start programmer edit section *** (Sotrudnik.Email Set end)

                // *** End programmer edit section *** (Sotrudnik.Email Set end)
            }
        }
        
        /// <summary>
        /// NomerKabineta.
        /// </summary>
        // *** Start programmer edit section *** (Sotrudnik.NomerKabineta CustomAttributes)

        // *** End programmer edit section *** (Sotrudnik.NomerKabineta CustomAttributes)
        public virtual int NomerKabineta
        {
            get
            {
                // *** Start programmer edit section *** (Sotrudnik.NomerKabineta Get start)

                // *** End programmer edit section *** (Sotrudnik.NomerKabineta Get start)
                int result = this.fNomerKabineta;
                // *** Start programmer edit section *** (Sotrudnik.NomerKabineta Get end)

                // *** End programmer edit section *** (Sotrudnik.NomerKabineta Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sotrudnik.NomerKabineta Set start)

                // *** End programmer edit section *** (Sotrudnik.NomerKabineta Set start)
                this.fNomerKabineta = value;
                // *** Start programmer edit section *** (Sotrudnik.NomerKabineta Set end)

                // *** End programmer edit section *** (Sotrudnik.NomerKabineta Set end)
            }
        }
        
        /// <summary>
        /// Sotrudnik.
        /// </summary>
        // *** Start programmer edit section *** (Sotrudnik.Dolzhnost CustomAttributes)

        // *** End programmer edit section *** (Sotrudnik.Dolzhnost CustomAttributes)
        [PropertyStorage(new string[] {
                "Dolzhnost"})]
        [NotNull()]
        public virtual UKTIO_App.Dolzhnost Dolzhnost
        {
            get
            {
                // *** Start programmer edit section *** (Sotrudnik.Dolzhnost Get start)

                // *** End programmer edit section *** (Sotrudnik.Dolzhnost Get start)
                UKTIO_App.Dolzhnost result = this.fDolzhnost;
                // *** Start programmer edit section *** (Sotrudnik.Dolzhnost Get end)

                // *** End programmer edit section *** (Sotrudnik.Dolzhnost Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sotrudnik.Dolzhnost Set start)

                // *** End programmer edit section *** (Sotrudnik.Dolzhnost Set start)
                this.fDolzhnost = value;
                // *** Start programmer edit section *** (Sotrudnik.Dolzhnost Set end)

                // *** End programmer edit section *** (Sotrudnik.Dolzhnost Set end)
            }
        }
        
        /// <summary>
        /// Sotrudnik.
        /// </summary>
        // *** Start programmer edit section *** (Sotrudnik.Organizaciya CustomAttributes)

        // *** End programmer edit section *** (Sotrudnik.Organizaciya CustomAttributes)
        [PropertyStorage(new string[] {
                "Organizaciya"})]
        [NotNull()]
        public virtual UKTIO_App.Organizaciya Organizaciya
        {
            get
            {
                // *** Start programmer edit section *** (Sotrudnik.Organizaciya Get start)

                // *** End programmer edit section *** (Sotrudnik.Organizaciya Get start)
                UKTIO_App.Organizaciya result = this.fOrganizaciya;
                // *** Start programmer edit section *** (Sotrudnik.Organizaciya Get end)

                // *** End programmer edit section *** (Sotrudnik.Organizaciya Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sotrudnik.Organizaciya Set start)

                // *** End programmer edit section *** (Sotrudnik.Organizaciya Set start)
                this.fOrganizaciya = value;
                // *** Start programmer edit section *** (Sotrudnik.Organizaciya Set end)

                // *** End programmer edit section *** (Sotrudnik.Organizaciya Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SotrudnikE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SotrudnikE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SotrudnikE", typeof(UKTIO_App.Sotrudnik));
                }
            }
            
            /// <summary>
            /// "SotrudnikL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SotrudnikL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SotrudnikL", typeof(UKTIO_App.Sotrudnik));
                }
            }
        }
    }
}
