//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKTIO_App
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Tip oborudovaniya.
    /// </summary>
    // *** Start programmer edit section *** (TipOborudovaniya CustomAttributes)

    // *** End programmer edit section *** (TipOborudovaniya CustomAttributes)
    [AutoAltered()]
    [Caption("Tip oborudovaniya")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TipOborudovaniyaE", new string[] {
            "Naimenovanie as \'Наименование\'"})]
    [View("TipOborudovaniyaL", new string[] {
            "Naimenovanie as \'Наименование\'"})]
    public class TipOborudovaniya : ICSSoft.STORMNET.DataObject
    {
        
        private string fNaimenovanie;
        
        // *** Start programmer edit section *** (TipOborudovaniya CustomMembers)

        // *** End programmer edit section *** (TipOborudovaniya CustomMembers)

        
        /// <summary>
        /// Naimenovanie.
        /// </summary>
        // *** Start programmer edit section *** (TipOborudovaniya.Naimenovanie CustomAttributes)

        // *** End programmer edit section *** (TipOborudovaniya.Naimenovanie CustomAttributes)
        [StrLen(255)]
        public virtual string Naimenovanie
        {
            get
            {
                // *** Start programmer edit section *** (TipOborudovaniya.Naimenovanie Get start)

                // *** End programmer edit section *** (TipOborudovaniya.Naimenovanie Get start)
                string result = this.fNaimenovanie;
                // *** Start programmer edit section *** (TipOborudovaniya.Naimenovanie Get end)

                // *** End programmer edit section *** (TipOborudovaniya.Naimenovanie Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TipOborudovaniya.Naimenovanie Set start)

                // *** End programmer edit section *** (TipOborudovaniya.Naimenovanie Set start)
                this.fNaimenovanie = value;
                // *** Start programmer edit section *** (TipOborudovaniya.Naimenovanie Set end)

                // *** End programmer edit section *** (TipOborudovaniya.Naimenovanie Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TipOborudovaniyaE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TipOborudovaniyaE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TipOborudovaniyaE", typeof(UKTIO_App.TipOborudovaniya));
                }
            }
            
            /// <summary>
            /// "TipOborudovaniyaL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TipOborudovaniyaL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TipOborudovaniyaL", typeof(UKTIO_App.TipOborudovaniya));
                }
            }
        }
    }
}
