//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKTIO_App
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T status.
    /// </summary>
    // *** Start programmer edit section *** (tStatus CustomAttributes)

    // *** End programmer edit section *** (tStatus CustomAttributes)
    public enum tStatus
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tStatus.VEkspluatacii CustomAttributes)

        // *** End programmer edit section *** (tStatus.VEkspluatacii CustomAttributes)
        [Caption("В эксплуатации")]
        VEkspluatacii,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tStatus.Prostaivaet CustomAttributes)

        // *** End programmer edit section *** (tStatus.Prostaivaet CustomAttributes)
        [Caption("Простаивает")]
        Prostaivaet,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tStatus.Neispravno CustomAttributes)

        // *** End programmer edit section *** (tStatus.Neispravno CustomAttributes)
        [Caption("Неисправно")]
        Neispravno,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tStatus.Spisano CustomAttributes)

        // *** End programmer edit section *** (tStatus.Spisano CustomAttributes)
        [Caption("Списано")]
        Spisano,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tStatus.VRemonte CustomAttributes)

        // *** End programmer edit section *** (tStatus.VRemonte CustomAttributes)
        [Caption("В ремонте")]
        VRemonte,
    }
}
